FactoryGirl.define do
  factory :hasuk_house do
    hasuk_name "MyString"
celPhone "MyString"
telPhone "MyString"
memo "MyString"
hasuk_kind "MyString"
gender "MyString"
size_from 1
size_to 1
floor_from 1
floor_to 1
building_age 1
remodeling 1
small_deposit 1
big_deposit 1
price_from 1
price_to 1
least_contract 1
extra_price1 "MyString"
extra_price2 "MyString"
extra_price3 "MyString"
extra_price4 "MyString"
extra_price5 "MyString"
meal1 "MyString"
meal2 "MyString"
meal3 "MyString"
meal4 "MyString"
meal_memo "MyString"
personal_option1 "MyString"
personal_option2 "MyString"
personal_option3 "MyString"
personal_option4 "MyString"
personal_option5 "MyString"
personal_option6 "MyString"
personal_option7 "MyString"
personal_option8 "MyString"
personal_option9 "MyString"
personal_option10 "MyString"
personal_option11 "MyString"
personal_option12 "MyString"
personal_option13 "MyString"
personal_option14 "MyString"
personal_option15 "MyString"
personal_option16 "MyString"
personal_option17 "MyString"
common_option1 "MyString"
common_option2 "MyString"
common_option3 "MyString"
common_option4 "MyString"
common_option5 "MyString"
common_option6 "MyString"
common_option7 "MyString"
common_option8 "MyString"
common_option9 "MyString"
common_option10 "MyString"
common_option11 "MyString"
common_option12 "MyString"
common_option13 "MyString"
internet "MyString"
post_description "MyString"
address "MyString"
lat 1.5
lng 1.5
univ_distance1 "MyString"
univ_distance2 "MyString"
univ_distance3 "MyString"
sogang_gate1 "MyString"
sogang_gate2 "MyString"
sogang_gate3 "MyString"
ewha_gate1 "MyString"
ewha_gate2 "MyString"
ewha_gate3 "MyString"
yonsei_gate1 "MyString"
yonsei_gate2 "MyString"
yonsei_gate3 "MyString"
distance_time1 1
distance_time2 1
distance_time3 1
distance1 1
distance2 1
distance3 1
room_img1 "MyString"
room_img2 "MyString"
room_img3 "MyString"
room_img4 "MyString"
room_img5 "MyString"
room_img6 "MyString"
room_img7 "MyString"
room_img8 "MyString"
room_price1 "MyString"
room_price2 "MyString"
room_price3 "MyString"
room_price4 "MyString"
room_price5 "MyString"
room_price6 "MyString"
room_price7 "MyString"
room_price8 "MyString"
room_description1 "MyString"
room_description2 "MyString"
room_description3 "MyString"
room_description4 "MyString"
room_description5 "MyString"
room_description6 "MyString"
room_description7 "MyString"
room_description8 "MyString"
common_img1 "MyString"
common_img2 "MyString"
common_img3 "MyString"
common_img4 "MyString"
meal_img1 "MyString"
meal_img2 "MyString"
meal_img3 "MyString"
meal_img4 "MyString"
discount_price 1
discount_rate 1
  end

end
